name: On Release Workflow
on:
  push: #This workflow will only trigger when a PR is merged into main. 
    branches: #Ideally all the pushes to the main branch should come from a PR merge.
      - main 
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' #using a specific distribution of jdk11 (AdoptOpenJDK)

    - name: Setting up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setting up Gradle Wrapper
      run: "gradle wrapper"

    - name: Validating Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setting up the SQLite database and Make
      run: | 
        sqlite3 -version
        make -version
        make clean-sqlite
        make sqlite-db-build
        make sqlite-db-populate

    - name: Running Tests
      run: "./gradlew test --tests=org.*"

    - name: After Success Submitting Code Coverage
      run: | #jacocoTestReport is for testing code coverage, submits the last report to the link
        ./gradlew jacocoTestReport
        bash <(curl -s https://codecov.io/bash)

  Docker-Integration-Test:
    needs: Unit-Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setting Up Docker Buildx #used for caching image layers, improves performance
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Get and Set Version
      run: |
        source ci/set-docker-image-version.sh
        echo "version=${DOCKER_IMG_VER}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ./Dockerfile
        push: true
        tags: ga4gh/ga4gh-starter-kit-common:${{ env.version }} #Using the correct version as the tag
        build-args: VERSION=${{ env.version }}
        cache-from: type=gha #GitHub Actions Cache Exporter
        cache-to: type=gha,mode=max

    - name: Running Tests
      run: |
        docker run --rm -d --name starter-kit-common-test-default -p 4500:4500 -p 4501:4501 ga4gh/ga4gh-starter-kit-common:${{ env.version }}
        docker run --rm -d --name starter-kit-common-test-custom -p 7000:7000 -p 7001:7001 ga4gh/ga4gh-starter-kit-common:${{ env.version }} --config ./src/test/resources/config/demo-config.yml
    
    - name: Gradle Integration Test
      run: ./gradlew test --tests=integration.*
